export {
  ApiError,
  ERROR_CODES,
  ERROR_STATUS,
  RETRYABLE_ERROR_CODES,
  buildErrorEnvelope,
  errorCodeSchema,
  errorEnvelopeSchema,
  isErrorCode,
  isRetryableErrorCode,
  registerErrorCodes,
  statusForErrorCode,
  type ErrorCode,
  type ErrorEnvelope,
  type ExtensionErrorCode,
} from './errors.ts'

export {
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  buildCursorPage,
  cursorPageSchema,
  cursorSchema,
  paginationQuerySchema,
  type CursorPage,
  type PaginationQuery,
} from './pagination.ts'

export {
  addMoney,
  currencyConversionSchema,
  currencySchema,
  minorUnitAmountSchema,
  money,
  moneySchema,
  revenueAmountsSchema,
  type CurrencyConversion,
  type Money,
  type RevenueAmounts,
} from './money.ts'

export {
  ACCURACIES,
  RESOLUTIONS,
  accuracySchema,
  dateRangeSchema,
  freshnessSchema,
  isHalfOpenContained,
  isValidTimezone,
  resolutionSchema,
  timezoneSchema,
  utcInstantSchema,
  type Accuracy,
  type DateRange,
  type Freshness,
  type Resolution,
  type UtcInstant,
} from './time.ts'

export {
  EVENT_LIMITS,
  EVENT_SCHEMA_VERSION,
  EVENT_TYPES,
  HISTORICAL_EVENT_TYPES,
  REALTIME_EVENT_TYPES,
  SERVER_ASSIGNED_CONTEXT_FIELDS,
  SERVER_ASSIGNED_EVENT_FIELDS,
  SUPPORTED_CONTENT_ENCODINGS,
  SUPPORTED_EVENT_SCHEMA_VERSIONS,
  VIEWPORT_CLASSES,
  WEB_VITAL_METRICS,
  clientContextSchema,
  clientEventSchema,
  engagementPayloadSchema,
  eventBatchAcceptedSchema,
  eventBatchSchema,
  eventIdSchema,
  eventNameSchema,
  eventPageSchema,
  eventPropertiesSchema,
  eventTypeSchema,
  heartbeatRequestSchema,
  historicalEventTypeSchema,
  interactionPayloadSchema,
  isHistoricalEventType,
  isUuidV7,
  persistedEventSchema,
  propertyKeySchema,
  propertyValueSchema,
  trackerConfigSchema,
  trackingKeySchema,
  webVitalPayloadSchema,
  type ClientContext,
  type ClientEvent,
  type ContentEncoding,
  type EventBatch,
  type EventBatchAccepted,
  type EventProperties,
  type EventType,
  type HeartbeatRequest,
  type HistoricalEventType,
  type PersistedEvent,
  type TrackerConfig,
  type ViewportClass,
  type WebVitalMetric,
} from './events.ts'

export {
  HEALTH_STATUSES,
  aggregateHealthStatus,
  dependencyHealthSchema,
  healthResponseSchema,
  healthStatusSchema,
  type DependencyHealth,
  type HealthResponse,
  type HealthStatus,
} from './health.ts'

export {
  MAX_HEARTBEAT_INTERVAL_SECONDS,
  MIN_HEARTBEAT_INTERVAL_SECONDS,
  PRESENCE_WINDOW_HEARTBEAT_RATIO,
  REALTIME_CONTROL_ACTIONS,
  REALTIME_CONTROL_REASONS,
  REALTIME_DEVICE_TYPES,
  REALTIME_FEED_MAX_EVENTS,
  REALTIME_PRESENT_MAX_VISITORS,
  REALTIME_SNAPSHOT_MAX_AGE_SECONDS,
  REALTIME_SNAPSHOT_TOP_N,
  publicRealtimeSnapshotSchema,
  realtimeControlSchema,
  realtimeCountrySchema,
  realtimeFeedEventSchema,
  realtimePresentVisitorSchema,
  realtimeSnapshotSchema,
  realtimeStreamEventSchema,
  realtimeTokenResponseSchema,
  type PublicRealtimeSnapshot,
  type RealtimeControl,
  type RealtimeControlAction,
  type RealtimeControlReason,
  type RealtimeDeviceType,
  type RealtimeFeedEvent,
  type RealtimePresentVisitor,
  type RealtimeSnapshot,
  type RealtimeStreamEvent,
  type RealtimeTokenResponse,
} from './realtime.ts'

export {
  OpenAnalyticsClient,
  type ApiPaths,
  type ClientOptions,
  type RequestOptions,
} from './client.ts'

export {
  ANALYTICS_FIXTURES,
  analyticsCustomEventsFixture,
  analyticsDevicesFixture,
  analyticsFunnelFixture,
  analyticsGeographyFixture,
  analyticsOverviewFixture,
  analyticsPagesFixture,
  analyticsPerformanceFixture,
  analyticsSessionsFixture,
  analyticsSourcesFixture,
  analyticsTimeseriesFixture,
  createdSiteFixture,
  expiredSiteInviteFixture,
  funnelDefinitionFixture,
  inviteResentFixture,
  publicDashboardSettingsFixture,
  publicDevicesFixture,
  publicGeographyFixture,
  publicOverviewFixture,
  publicPagesFixture,
  publicRealtimeSnapshotFixture,
  publicRealtimeWidgetFixture,
  publicSessionsFixture,
  publicSiteIdentityAnonymousFixture,
  publicSiteIdentityFixture,
  publicSourcesFixture,
  publicTimeseriesFixture,
  publicWidgetFixture,
  realtimeControlFixture,
  realtimeSnapshotFixture,
  realtimeTokenResponseFixture,
  siteInviteFixture,
  userPreferencesFixture,
  widgetFixture,
} from './fixtures.ts'

export type { components, operations, paths } from './generated/api.ts'

/** Public product API version. Docs snapshot 02 §18: business routes are versioned. */
export const API_VERSION = 'v1'
